name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Quay
      uses: docker/login-action@v3
      with:
        registry: quay.nextania.com
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: quay.nextania.com/nextania/account:git
